# Generated by Django 5.2 on 2026-07-02 18:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrendaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prenda', models.CharField(max_length=120)),
                ('nombre_normalizado', models.CharField(editable=False, max_length=120)),
                ('talla_prenda', models.CharField(max_length=40)),
                ('talla_normalizada', models.CharField(editable=False, max_length=40)),
                ('cantidad_prenda', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_actual', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_critico', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('codigo_barra', models.CharField(db_index=True, max_length=80, unique=True)),
                ('codigo_qr', models.CharField(max_length=255, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre_normalizado', 'talla_normalizada'],
                'indexes': [models.Index(fields=['nombre_normalizado', 'talla_normalizada'], name='inventario__nombre__00d853_idx'), models.Index(fields=['stock_actual'], name='inventario__stock_a_100550_idx')],
                'constraints': [models.UniqueConstraint(fields=('nombre_normalizado', 'talla_normalizada'), name='unique_prenda_talla_normalizada'), models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='inventario_stock_actual_no_negativo')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso desde proveedor'), ('entrega', 'Entrega a usuario final'), ('recepcion', 'Recepcion/devolucion'), ('ajuste', 'Ajuste de inventario')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_antes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_despues', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prendas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.prendainventario')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['tipo', 'creado_en'], name='inventario__tipo_b63d57_idx'), models.Index(fields=['prenda', 'creado_en'], name='inventario__prenda__350314_idx')],
            },
        ),
    ]
