# Generated by Django 5.2 on 2026-07-03 18:18

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='estado_envio',
            field=models.CharField(choices=[('no_aplica', 'No aplica'), ('en_transito', 'En transito'), ('recibido', 'Recibido'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado')], db_index=True, default='no_aplica', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fecha_estado_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['estado_envio', 'creado_en'], name='inventario__estado__5ffee9_idx'),
        ),
    ]
