# Generated by Django 5.2 on 2026-07-03 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario_estado_envio_and_more'),
        ('user', '0002_personalempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='destinatario_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='user.personalempresa'),
        ),
    ]
