# Generated by Django 5.2 on 2026-07-07 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientoinventario_destinatario_personal'),
        ('user', '0002_personalempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteEntregaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='application/pdf', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_inventario', to='user.personalempresa')),
                ('movimientos', models.ManyToManyField(related_name='comprobantes_entrega', to='inventario.movimientoinventario')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_inventario_supervisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['creado_en'], name='inventario__creado__193802_idx'), models.Index(fields=['destinatario_personal', 'creado_en'], name='inventario__destina_ca97d5_idx'), models.Index(fields=['supervisor', 'creado_en'], name='inventario__supervi_31d884_idx')],
            },
        ),
    ]
