# Generated by Django 5.2 on 2026-07-13 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_autorizacionentregainventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_1', models.EmailField(blank=True, default='', max_length=254)),
                ('email_2', models.EmailField(blank=True, default='', max_length=254)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_alerta_stock_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de alerta de stock',
                'verbose_name_plural': 'Configuración de alertas de stock',
            },
        ),
        migrations.CreateModel(
            name='RegistroAlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.PositiveIntegerField()),
                ('stock_critico', models.PositiveIntegerField()),
                ('destinatarios', models.JSONField(default=list)),
                ('enviado', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_stock', to='inventario.movimientoinventario')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_stock', to='inventario.prendainventario')),
            ],
            options={
                'ordering': ('-creado_en', '-id'),
            },
        ),
    ]
