# Generated by Django 5.2 on 2025-04-26 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_fijo', '0001_initial'),
        ('supervision', '0002_remove_documentacion_supervision_delete_cargofijo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCargoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('OP', 'Operativo'), ('NOP', 'No Operativo'), ('NA', 'No Aplica')], max_length=3)),
                ('cargo_fijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_fijo.cargofijoitem')),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_cargos_fijos', to='supervision.supervision')),
            ],
        ),
    ]
