# Generated by Django 5.2 on 2025-04-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_fijo', '0003_remove_estadocargofijo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocargofijo',
            name='estado',
            field=models.CharField(choices=[('buen estado', 'Buen estado'), ('mal estado', 'Mal estado'), ('inutilizable', 'Inutilizable')], default='buen estado', max_length=20),
        ),
    ]
