# Generated by Django 5.2 on 2025-04-26 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervision', '0002_remove_documentacion_supervision_delete_cargofijo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDocumentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_revisada', models.PositiveIntegerField(default=0)),
                ('validez', models.BooleanField(default=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentacion.documentoitem')),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_documentos', to='supervision.supervision')),
            ],
        ),
    ]
