# Generated by Django 5.2 on 2025-12-26 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0001_initial'),
        ('instalacion', '0003_alter_instalacion_zona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('categoria', models.CharField(blank=True, default='', max_length=80)),
                ('clasificacion', models.CharField(choices=[('interno', 'Interno'), ('confidencial', 'Confidencial')], default='confidencial', max_length=20)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='instalacion.instalacion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
