# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentacion", "0002_documentoinstalacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoinstalacion",
            name="estado_directiva",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sin_tramitar", "Sin tramitar"),
                    ("tramitada", "Tramitada"),
                    ("aprobada", "Aprobada"),
                ],
                default="sin_tramitar",
                max_length=20,
            ),
        ),
    ]
