# Generated by Django 5.2 on 2025-04-26 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instalacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('novedades', models.TextField(blank=True, null=True)),
                ('solicitudes', models.TextField(blank=True, null=True)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisiones', to='instalacion.instalacion')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisiones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('OP', 'Operativo'), ('NOP', 'No Operativo'), ('NA', 'No Aplica')], max_length=3)),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentaciones', to='supervision.supervision')),
            ],
        ),
        migrations.CreateModel(
            name='CargoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('OP', 'Operativo'), ('NOP', 'No Operativo'), ('NA', 'No Aplica')], max_length=3)),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_fijos', to='supervision.supervision')),
            ],
        ),
    ]
