# Generated by Django 5.2 on 2025-04-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentacion',
            name='supervision',
        ),
        migrations.DeleteModel(
            name='CargoFijo',
        ),
        migrations.DeleteModel(
            name='Documentacion',
        ),
    ]
