# Generated by Django 5.2 on 2025-04-27 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0002_remove_documentacion_supervision_delete_cargofijo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='supervision.supervision')),
            ],
        ),
    ]
