# Generated by Django 5.2 on 2026-08-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0005_supervisionactiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervision',
            name='estado_solicitud',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('gestionado', 'Gestionado'), ('entregado', 'Entregado'), ('denegado', 'Denegado')], default='pendiente', max_length=20),
        ),
    ]
