# Generated by Django 5.2 on 2026-09-24 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0006_supervision_estado_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendicionGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_nombre', models.CharField(max_length=301)),
                ('instalacion', models.CharField(max_length=220)),
                ('persona', models.CharField(max_length=220)),
                ('storage_key', models.CharField(max_length=500)),
                ('creada_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendiciones_gastos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada_en', '-id'],
            },
        ),
    ]
