# Generated by Django 5.2 on 2026-09-24 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0007_rendiciongasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendiciongasto',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rendiciongasto',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
