# Generated by Django 5.2 on 2026-09-26 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0008_rendicion_monto_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendiciongasto',
            name='depositante',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='rendiciongasto',
            name='gasto_depositado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rendiciongasto',
            name='monto_depositado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
