# Generated by Django 5.2 on 2026-09-30 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_id', models.UUIDField(unique=True)),
                ('supervisor_nombre', models.CharField(max_length=310)),
                ('tipo', models.CharField(choices=[('recepcion', 'Recepción'), ('entrega', 'Entrega')], max_length=10)),
                ('kilometraje', models.PositiveIntegerField()),
                ('gata', models.BooleanField()),
                ('llave_cruz', models.BooleanField()),
                ('extintor', models.BooleanField()),
                ('triangulo', models.BooleanField()),
                ('resumen', models.TextField(max_length=5000)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('recepcion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrega', to='vehiculos.movimientovehiculo')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FotoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista', models.CharField(choices=[('frontal', 'Frontal'), ('trasera', 'Trasera'), ('izquierdo', 'Izquierdo'), ('derecho', 'Derecho'), ('tablero', 'Tablero'), ('extra', 'Extra')], max_length=10)),
                ('storage_key', models.CharField(max_length=255)),
                ('tiene_novedad', models.BooleanField(default=False)),
                ('novedad', models.TextField(blank=True, max_length=3000)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='vehiculos.movimientovehiculo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=12, unique=True)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0)),
                ('kilometraje_mantencion', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('supervisor_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_en_uso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['patente'],
            },
        ),
        migrations.AddField(
            model_name='movimientovehiculo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='vehiculos.vehiculo'),
        ),
    ]
