# Generated by Django 5.2 on 2026-05-27 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instalacion', '0004_instalacion_estado_directiva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('pre_informe', 'Pre informe'), ('vulnerabilidades', 'Reporte de vulnerabilidades')], max_length=30)),
                ('zona', models.CharField(blank=True, default='', max_length=80)),
                ('autor_nombre', models.CharField(max_length=255)),
                ('autor_cargo', models.CharField(blank=True, default='', max_length=150)),
                ('descripcion_hechos', models.TextField(blank=True, default='')),
                ('analisis_previo', models.TextField(blank=True, default='')),
                ('analisis_final_usuario', models.TextField(blank=True, default='')),
                ('personal_presente', models.TextField(blank=True, default='')),
                ('personal_policial_presente', models.BooleanField(default=False)),
                ('carabinero_cargo', models.CharField(blank=True, default='', max_length=150)),
                ('patente_patrulla', models.CharField(blank=True, default='', max_length=30)),
                ('numero_carro_policial', models.CharField(blank=True, default='', max_length=30)),
                ('criticidad_general', models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], default='', max_length=20)),
                ('resumen_ejecutivo', models.TextField(blank=True, default='')),
                ('conclusion_profesional', models.TextField(blank=True, default='')),
                ('riesgos_detectados', models.JSONField(blank=True, default=list)),
                ('recomendaciones_ia', models.JSONField(blank=True, default=list)),
                ('matriz_riesgo', models.JSONField(blank=True, default=list)),
                ('texto_final_pdf', models.TextField(blank=True, default='')),
                ('respuesta_ia_raw', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'Generado'), ('error_ia', 'Error IA')], default='borrador', max_length=20)),
                ('fecha_emision', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_informes', to='instalacion.instalacion')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_informes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ImagenReporteInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('recomendacion_usuario', models.TextField(blank=True, default='')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='reportes.reporteinforme')),
            ],
            options={
                'ordering': ('orden', 'id'),
                'unique_together': {('reporte', 'orden')},
            },
        ),
    ]
