# Generated by Django 5.2 on 2026-05-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteinforme',
            name='archivo_origen_mime_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='reporteinforme',
            name='archivo_origen_nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reporteinforme',
            name='archivo_origen_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporteinforme',
            name='archivo_origen_storage_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reporteinforme',
            name='texto_extraido_origen',
            field=models.TextField(blank=True, default=''),
        ),
    ]
