# Generated by Django 5.2 on 2025-04-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='zona',
            field=models.CharField(choices=[('norte', 'Norte'), ('centro', 'Centro'), ('sur', 'Sur')], default='centro', max_length=10),
        ),
    ]
