# Generated by Django 5.2 on 2025-12-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0002_instalacion_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='zona',
            field=models.CharField(choices=[('norte', 'Norte'), ('centro', 'Centro'), ('sur', 'Sur'), ('tw', 'Tw')], default='centro', max_length=10),
        ),
    ]
