# Generated by Django 5.2 on 2026-05-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0003_alter_instalacion_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='estado_directiva',
            field=models.CharField(choices=[('no_existe', 'No existe'), ('vencida', 'Vencida'), ('tramitada', 'Tramitada'), ('rechazada', 'Rechazada'), ('aprobada', 'Aprobada')], default='no_existe', max_length=20),
        ),
    ]
