# Generated by Django 5.2 on 2026-07-10 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instalacion', '0004_instalacion_estado_directiva'),
        ('user', '0002_personalempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato de trabajo'), ('riohs', 'Reglamento interno (RIOHS)')], max_length=20)),
                ('nombre_original', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('texto_extraido', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_laborales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hecho', models.DateField()),
                ('supervisor', models.CharField(max_length=220)),
                ('tipo_incumplimiento', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('reincidencia', models.BooleanField(default=False)),
                ('antecedentes', models.TextField(blank=True)),
                ('ciudad', models.CharField(default='Santiago', max_length=120)),
                ('carta', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amonestaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amonestaciones', to='instalacion.instalacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amonestaciones', to='user.personalempresa')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amonestaciones_contrato', to='amonestaciones.documentolaboral')),
                ('riohs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amonestaciones_riohs', to='amonestaciones.documentolaboral')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
    ]
