# Generated by Django 5.2 on 2026-08-11 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(max_length=180)),
                ('price', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=800)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('draft', 'Borrador'), ('inactive', 'Inactiva')], default='active', max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('section', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Visita'), ('section_view', 'Sección visitada'), ('click', 'Clic')], db_index=True, max_length=20)),
                ('section', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target', models.CharField(blank=True, db_index=True, max_length=100)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, max_length=20)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'event_type'], name='vivadent_an_created_067088_idx'), models.Index(fields=['section', 'created_at'], name='vivadent_an_section_fe22b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.SlugField(max_length=100)),
                ('key', models.SlugField(max_length=100)),
                ('value', models.TextField(max_length=3000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'key'],
                'constraints': [models.UniqueConstraint(fields=('section', 'key'), name='vivadent_unique_site_text')],
            },
        ),
        migrations.CreateModel(
            name='VivadentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vivadent_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
