# Generated by Django 5.2 on 2026-07-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(db_index=True, max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=220)),
                ('ubicacion', models.CharField(blank=True, max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre_completo'],
                'indexes': [models.Index(fields=['ubicacion'], name='user_person_ubicaci_0046d0_idx'), models.Index(fields=['activo'], name='user_person_activo_74a9e0_idx')],
            },
        ),
    ]
